export interface ISkifield{
    _id: string,
    name: string,
    country: string,
    url: string,
    region: string,
    lan: string,
    elevation: string,
    topToBottom: number,
    highest: number,
    lowest: number,
    totalSlopes: number,
    blueSlopes: number,
    redSlopes: number,
    blackSlopes: number,
    skiLifts: number,
    image: string,
    trailMap: string,
    description: string,
    rating: number,
    adultSkiPass: number,
    youthSkiPass: number,
    generalSeason: string,
    openingTimes: string,
    nearbyTown1: string,
    nearbyTown2: string,
    lat: number,
    lng: number,
    position: {
        lat: number,
        lng: number
    }
    user_id: string, 
}

export interface IFavourite{
    _id: string,
    name: string,
    country: string,
    url: string,
    region: string,
    lan: string,
    elevation: string,
    topToBottom: number,
    highest: number,
    lowest: number,
    totalSlopes: number,
    blueSlopes: number,
    redSlopes: number,
    blackSlopes: number,
    skiLifts: number,
    image: string,
    trailMap: string,
    description: string,
    rating: number,
    adultSkiPass: number,
    youthSkiPass: number,
    generalSeason: string,
    openingTimes: string,
    nearbyTown1: string,
    nearbyTown2: string,
    lat: number,
    lng: number,
}

export interface IUser{
    _id: string,
    email: string,
    username: string,
    password: string,
    role: string,
    image: string,
    favourites: [string],
    beenHere: [string],
    skifieldId: string,
}


